#! /bin/sh
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2018, Arm Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# DO NOT REMOVE THIS COMMENT: LISA-HOOK

# Git post-checkout hook that checks if lisa-install needs to be run again due
# to updated setup.py files

PREVIOUS_HEAD=$1
NEW_HEAD=$2
IS_BRANCH_CHECKOUT=$3

echo -e "\033[31m"
echo "WARNING: shell state might go out of sync with lisa-shell."
echo -e "\033[0m"
echo "Please source init_env again:"
echo "    \$ env -i $SHELL"
echo "    \$ source init_env"

if which check-setuppy >/dev/null 2>&1; then
    check-setuppy --current-rev "$NEW_HEAD"
fi

# Make sure we always exit with 0 return code, otherwise it might break
# rebasing
exit 0
