# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: doc/conf.py
  # intersphinx is broken for some dependencies like devlib
  fail_on_warning: false


# Only build default HTML to save some build time
formats: []

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: doc/doc_requirements.txt
