[package]
name = "lisakmod"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
# hashbrown = "0.15"
lisakmodprocmacro = { path = "../proc_macros/lisakmodprocmacro" }
paste = "1.0"

[profile.release]
panic = 'abort'
strip = "debuginfo"

[profile.dev]
panic = 'abort'
