cargo-features = ["edition2024"]

[package]
name = "lisakmod"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
# hashbrown = "0.15"
lisakmod_macros = { path = "../lisakmod-macros" }

[profile.release]
panic = 'abort'
strip = "debuginfo"

[profile.dev]
panic = 'abort'
