/* SPDX-License-Identifier: GPL-2.0 */

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by Rust cbindgen. Don't modify this manually. */


extern uint64_t myc_callback(uint64_t x);

uint64_t do_rust_tests(void) ;

