/* SPDX-License-Identifier: GPL-2.0 */

/* Basic glue between Rust runtime and kernel functions */
#include "rust/lisakmod/bindings.h"

/* C shims generated by the lisakmod_macros::inlinec module */
#include "generated/rust/rust_c_shims.c"
