/* SPDX-License-Identifier: GPL-2.0 */
#include "main.h"
#include "rust/lisakmod/cbindgen.h"

/* Basic glue between Rust runtime and kernel functions */

/* C shims generated by the lisakmodprocmacro::inlinec module */
#include "generated/rust/rust_c_shims.h"
