/* SPDX-License-Identifier: GPL-2.0 */
#include "main.h"
#include "rust/lisakmod/bindings.h"

/* Basic glue between Rust runtime and kernel functions */

/* C shims generated by the lisakmod_macros::inlinec module */
#include "rust/lisakmod-macros/cffi.h"
#include "generated/rust/rust_c_shims.c"
