#!/bin/bash

NETIF=${1:-eth0}

# By default use internal libraries
DEVMODE=${DEVMODE:-1}

# Get the IP Address of the local Ethernet interface
IPADDR=$(ifconfig $NETIF 2>/dev/null  | \
	awk '/inet / {print $2}' | \
	sed 's/addr://')

if [ "x$IPADDR" == "x" ]; then
    echo
    echo "$NETIF is not a valid network interface"
    echo
    echo "Usage: $0 <NETIF>"
    echo " NETIF - The network interface to start the server on"
    echo
    exit 1
fi

# Get base installation path of LISA
cd "$(dirname $0)/.." &>/dev/null
LISA_HOME="$(pwd)"
cd - $>/dev/null
PYDIR="$LISA_HOME/ipynb"
LOGFILE="$PYDIR/server.log"

export PYTHONPATH=''
export PYTHONPATH=$LISA_HOME/libs/utils:$PYTHONPATH
export PYTHONPATH=$LISA_HOME/libs/wlgen:$PYTHONPATH

if [ "x$DEVMODE" == "x1" ]; then
	export PYTHONPATH=$LISA_HOME/libs/devlib:$PYTHONPATH
	export PYTHONPATH=$LISA_HOME/libs/trappy:$PYTHONPATH
	export PYTHONPATH=$LISA_HOME/libs/bart:$PYTHONPATH

	echo
	echo 'Developer mode ENABLED, using local libraries'
	if [ ! -f libs/devlib/README.rst ]; then
		echo 'Initializing submodules...'
		git submodule init
	fi
	echo 'Update submodules if required'
	git submodule update
	echo 'DONE'
fi

echo 'Starting IPython Notebook server...'
echo "  IP Address :  http://$IPADDR:8888/"
echo '  Folder     : ' $PYDIR
echo '  Logfile    : ' $LOGFILE
echo '  PYTHONPATH : '
echo -e "\t${PYTHONPATH//:/\\n\\t}"

cd $PYDIR
nohup ipython notebook --ip=$IPADDR &>$LOGFILE &
cd - >/dev/null
echo

