#!/bin/bash

NETIF=${1:-eth0}

# Get the IP Address of the local Ethernet interface
IPADDR=$(ifconfig $NETIF 2>/dev/null  | \
	awk '/inet / {print $2}' | \
	sed 's/addr://')

if [ "x$IPADDR" == "x" ]; then
    echo
    echo "$NETIF is not a valid network interface"
    echo
    echo "Usage: $0 <NETIF>"
    echo " NETIF - The network interface to start the server on"
    echo
    exit 1
fi

PYDIR=$(pwd)
BASEDIR=$(dirname $PYDIR)

export PYTHONPATH=''
export PYTHONPATH=`pwd`/../libs/utils:$PYTHONPATH
export PYTHONPATH=`pwd`/../libs/wlgen:$PYTHONPATH

if [ "x$DEVMODE" == "x1" ]; then
	export PYTHONPATH=`pwd`/../libs/devlib:$PYTHONPATH
	export PYTHONPATH=`pwd`/../libs/trappy:$PYTHONPATH
	export PYTHONPATH=`pwd`/../libs/bart:$PYTHONPATH

	echo
	echo 'Developer mode ENABLED, using libraries provided by submodules'
	echo 'PYTHONPATH: '
	echo $PYTHONPATH
	echo

	if [ ! -f libs/devlib/README.rst ]; then
		echo 'Initializing submodules...'
		git submodule init
	fi
	echo 'Update submodules if required'
	git submodule update
	echo 'DONE'
fi

echo 'Starting IPython Notebook server...'
echo "  IP Address :  http://$IPADDR:8888/"
echo '  Folder     : ' $PYDIR
echo '  PYTHONPATH : ' $PYTHONPATH

nohup ipython notebook --ip=$IPADDR &
echo
echo
echo

