#!/bin/bash

NETIF=${1:-eth0}

# Get the IP Address of the local Ethernet interface
IPADDR=$(ifconfig $NETIF 2>/dev/null  | \
	awk '/inet / {print $2}' | \
	sed 's/addr://')

if [ "x$IPADDR" == "x" ]; then
    echo
    echo "$NETIF is not a valid network interface"
    echo
    echo "Usage: $0 <NETIF>"
    echo " NETIF - The network interface to start the server on"
    echo
    exit 1
fi

PYDIR=$(pwd)
BASEDIR=$(dirname $PYDIR)
export PYTHONPATH=$BASEDIR/libs/utils:$PYTHONPATH
export PYTHONPATH=$BASEDIR/libs/wlgen:$PYTHONPATH

echo 'Starting IPython Notebook server...'
echo '  IP Address : ' $IPADDR
echo '  Folder     : ' $PYDIR
echo '  PYTHONPATH : ' $PYTHONPATH

nohup ipython notebook --ip=$IPADDR &
echo
echo
echo


