#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2015, ARM Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

################################################################################
# Other internal configurations
################################################################################
BASE_DIR=$(dirname $(realpath $0))
source "${BASE_DIR}/helpers"


################################################################################
# Builds configuration
################################################################################

PLATFORM=${PLATFORM:-'hikey960_android-4.4'}
KERNEL_SRC=${KERNEL_SRC:-$BASE_DIR/kernel}
SERIES=${SERIES:-''}
WA_AGENDA=${WA_AGENDA:-''}
TEST_CMD=${TEST_CMD:-'echo "Test DONE!"'}

if [ -z "$ANDROID_HOME" ]; then
	ADB=${ADB:-$(which adb)}
	FASTBOOT=${FASTBOOT:-$(which fastboot)}
else
	ADB=${ADB:-$ANDROID_HOME/platform-tools/adb}
	FASTBOOT=${FASTBOOT:-$ANDROID_HOME/platform-tools/fastboot}
fi

EMETER=${EMETER:-'ACME'}
ACME_IP=${ACME_IP:-'192.168.0.1'}
ACME_USB=${ACME_USB:-'device1'}
ACME_CHANNELS=${ACME_CHANNELS:-'0'}

RESULTS=${RESULTS:-$LISA_HOME/results/wltests}
FORCE=${FORCE:-0}
DEVICE=${DEVICE:-'C00010FFBAADA555'}
REBOOT_TIMEOUT=${REBOOT_TIMEOUT:-180}

DRYRUN=${DRYRUN:-0}

################################################################################
# Check configuration
################################################################################

usage() {
	cat <<EOF

Usage: [ENV]... $(basename $0) -k KERNEL_SRC -s SERIES -p PLATFORM [-a WA_AGENDA | -t TEST_CMD] [OPTIONS]..."

Checkout, compile, flash a predefined set of kernel COMMITS and run a custom
SCRIPT for each of them.

Kernel to test:

    -k, --kernel_src PATH	The kernel source tree to use.
				Default: KERNEL_SRC=../kernel

    -s, --series PATH		The series of commits to test.
				This is the patch of the file containing a list
				of patches to test. This list can be generated
				with a command like:

				  git log --no-color --oneline <revision range>

				The list obtained by the previous command can
				be enriched by adding an "ID:" in front of each
				line.
				If an "ID:" column is present, the commits will
				be considered in progressive "ID:" order while
				discarding those with ID=00:
				Default: SERIES=''

Target device to use for kernel testing:

    -p, --platform		The platform to target.
				Available platforms are the subfolders of the
				top level "platforms" folder.
				Default: PLATFORM=juno_android-4.4

	--supported_platforms	Print a list of supported platforms which can
				are valid values for the -p parameter.

    -d, --device		The Android device to target.
				If ANDROID_DEVICE is set, its value will be used
				as a default.
				Default DEVICE=$ANDROID_DEVICE

Tests to run for each kernel tested on target:

    -a, --wa_agenda PATH	The path of a WA agenda describing the experiments
				to be executed for each test in SERIES.
				Default: WA_AGENDA=''

	--available_agendas	Print a list of available agendas.

    -t, --test_cmd		The command line of A custom test script to run
				for each kernel.
				Default: TEST_CMD='echo "Test DONE!"'

Additional arguments:

	--adb			The ADB binary to use.
				Default: ADB=[ANDROID_HOME/platform-tools/adb|\$(which adb)]
	--fastboot		The FASTBOOT binary to use.
				Default: FASTBOOT=[ANDROID_HOME/platform-tools/fatboot|\$(which fatboot)]

	--emeter		The Energy Meter used to power-cycle the device.
				Default: EMETER=ACME
	--acme_ip		The IP address of an ACME energy meter.
				Default: ACME_IP=192.168.0.1
	--acme_usb		The ACME channel used to control a USB
				assthrought connetion.
				Default ACME_USB=device1
	--acme_channels		A space separated list for channels ID to sample.
				For example, --acme_channels "0 2" will enabled
				sampling on:
				   iio:device0 and iio:device2
				Default: ACME_CHANNELS="0"

	--results PATH		The base path for all the generated result folders.
				Default: RESULTS='$RESULTS'

	--force			Force execution with a non empty RESULTS folder.

	--reboot_timeout	Maximum number of seconds to wait for a device
				to complete the boot.
				Default REBOOT_TIMEOUT=180

	--dryrun		Don't actually run any command
				Deafult: DRYRUN=0

Example command:

  $> lisa-wltest-series --kernel_src /path/to/your/kernel/hikey-linaro \\
	--series /path/to/your/series.sha1 --platform hikey960_android-4.4 \\
	--wa_agenda /path/to/your/agenda.yaml

EOF
}

ASSETS_REQUIRED="definitions build_images flash_images"
list_supported_platforms() {
	echo
	echo "Supported platforms are:"
	ls $BASE_DIR/platforms | while read PLAT; do
		RESULT=$OK
		for ASSET in $ASSETS_REQUIRED; do
			if [ ! -f $BASE_DIR/platforms/$PLAT/$ASSET ]; then
				RESULT=$ENOENT; break;
			fi
		done
		[ $RESULT == $OK ] || continue
		echo " - $PLAT"
	done
	echo
	echo "New platforms can be added by copying and adapting one of the folder available"
	echo "under the this base path:"
	echo "   $BASE_DIR/platforms"
	echo
}

list_available_agendas() {
	echo
	echo "Available agendas are: "
	for AGENDA in $(ls $BASE_DIR/agendas/*.yaml); do
		echo " - $(basename $AGENDA)"
	done
	echo
	echo "New agendas can be added by copying and adapting one of those available"
	echo "under the folder:"
	echo "   $BASE_DIR/agendas"
	echo
}

while [[ $# -gt 0 ]]; do
	case $1 in

	# Kernel options
	-k|--kernel_src)
		KERNEL_SRC=$2
		shift
	;;
	-s|--series)
		SERIES=$2
		shift
	;;

	# Platform options
	-p|--platform)
		PLATFORM=$2
		shift
	;;
	-d|--device)
		DEVICE=$2
		shift
	;;
	--supported_platforms)
		list_supported_platforms
		exit $OK
	;;

	# Tests options
	-a|--wa_agenda)
		WA_AGENDA=$2
		shift
	;;
	-t|--test_cmd)
		TEST_CMD=$2
		shift
	;;
	--available_agendas)
		list_available_agendas
		exit $OK
	;;


	# Tools options
	--adb)
		ADB=$2
		shift
	;;
	--fastboot)
		FASTBOOT=$2
		shift
	;;

	# Energy meter options
	--emeter)
		EMETER=$2
		shift
	;;
	--acme_ip)
		ACME_IP=$2
		shift
	;;
	--acme_usb)
		ACME_USB=$2
		shift
	;;
	--acme_channels)
		ACME_CHANNELS=$2
		shift
	;;

	# Execution customization
	--results)
		RESULTS=$2
		shift
	;;
	--reboot_timeout)
		REBOOT_TIMEOUT=$2
		shift
	;;
	--force)
		FORCE=1
	;;
	--dryrun)
		DRYRUN=1
	;;

	# Usage notes
	-h|--help)
		usage
		exit $OK
	;;
	*)
		c_error "Unknown option: $1"
		usage
		exit $EAGAIN
	;;
	esac
	shift # past argument or value
done

# Prepare DEVICE
if [ "x$DEVICE" == "xC00010FFBAADA555" ]; then
	if [ -z "$ANDROID_DEVICE" ]; then
		echo
		c_error "Target device not set"
		echo
		c_info "A target device must be specified by either"
		c_info " - setting a value for \$ANDROID_SERIAL"
		c_info " - setting a value for \$DEVICE"
		c_info " - passing a --device option"
		echo
	else
		DEVICE=$ANDROID_SERIAL
	fi
	exit $EINVAL
fi
export WA_LOCAL_CONF=$RESULTS/config_local.yaml

# Prepare PLATFORM
export PLATFORM_PATH=$BASE_DIR/platforms/$PLATFORM
for ASSET in $ASSETS_REQUIRED; do
if [ ! -f $PLATFORM_PATH/$ASSET ]; then
	echo
	c_error "The specified PLATFORM=$PLATFORM is not supported, or it does not provide a [$ASSET] file"
	list_supported_platforms
	exit $EINVAL
fi
done
export PLATFORM_OVERLAY_PATH=$PLATFORM_PATH

# Prepare KERNEL_SRC
export KERNEL_SRC=$(realpath -s $KERNEL_SRC)
grep -E "mainmenu .* Kernel Configuration" $KERNEL_SRC/Kconfig &>/dev/null
if [ $? -ne 0 ]; then
	echo
	c_error "The \$KERNEL_SRC|--kernel_src seems not to a valid kernel source tree path"
	echo
	exit $EINVAL
fi

# Prepare SERIES
if [ -z "$SERIES" ]; then
	echo
	c_error "A valid commit series should be defined by \$SERIES|--series"
	echo
	exit $EINVAL
fi
if [ ! -f $SERIES ]; then
	echo
	c_error "\$SERIES|--series points to a non existing commit series"
	echo
	exit $ENOENT
fi

# Prepare RESULTS
if [ $FORCE -eq 0 -a \
	-d $RESULTS -a \
	"$(ls -A $RESULTS)" ]; then
	echo
	c_warning "The results folder:"
	c_warning "   $RESULTS"
	c_warning "already exists and is not empty."
	echo
	c_info "Use \$FORCE|--force if you want to override results in that same folder"
	echo
	exit $EINVAL
fi
mkdir -p $RESULTS &>/dev/null
cat >$WA_LOCAL_CONF <<EOF
# Automatically generated ADB device configuration based on test_series options
device_config:
  device: $DEVICE

EOF

config_emeter_acme() {
	# Generate a WA configuration fragment for the ACME cape and ADB
	IIO_DEVICES=""
	for CH in $ACME_CHANNELS; do
		IIO_DEVICES="$IIO_DEVICES \"iio:device$CH\", "
	done
	cat >>$WA_LOCAL_CONF <<EOF
# Automatically generated ACME configuration based on test_series options
energy_measurement:
  instrument: acme_cape
  instrument_parameters:
    host: $ACME_IP
    # If collecting on multiple channels, or another channel than iio:device0,
    # set them here:
    iio_devices: [$IIO_DEVICES]

EOF
}

config_emeter_monsoon() {
	# Generate a WA configuration fragment for the MONSOON energy meter
	cat >>$WA_LOCAL_CONF <<EOF
# Automatically generated MONSOON configurations
energy_measurement:
  instrument: monsoon

EOF
}

# Prepare WA_AGENDA (if specified it override the TEST_CMD)
if [ ! -z $WA_AGENDA ]; then
	if [ ! -f $WA_AGENDA ]; then
		echo
		c_error "The \$WA_AGENDA|--wa_agenda is not a valid path for a WA agenda"
		list_available_agendas
		exit $INVAL
	fi
	TEST_CMD_RESULTS="$RESULTS/wa.\${COMMIT_SHA1:0:7}_\${COMMIT_NAME}"

	# Configure WA command
	# Depending on the EnergyMeter in use, an auxiliary configuration file
	# can be required.
	if [ "x$EMETER" == "xACME" ]; then
		config_emeter_acme
		TEST_CMD="wa run -f -d \"$TEST_CMD_RESULTS\" -c \"$WA_LOCAL_CONF\" \"$WA_AGENDA\""
	fi
	if [ "x$EMETER" == "xMONSOON" ]; then
		config_emeter_monsoon
		TEST_CMD="wa run -f -d \"$TEST_CMD_RESULTS\" -c \"$WA_LOCAL_CONF\" \"$WA_AGENDA\""
	fi
fi

# Prepare ADB and FASTBOOT commands to target the specified device
if [ ! -f $ADB ]; then
	c_error "ADB command [$ADB] not found"
	exit $EINVAL
fi
if [ ! -f $FASTBOOT ]; then
	c_error "FASTBOOT command [$FASTBOOT] not found"
	exit $EINVAL
fi
export ADB="$ADB -s $DEVICE"
export FASTBOOT="$FASTBOOT -s $DEVICE"

# Prepare Energy Meter device
case $EMETER in
'ACME')
	EMETER_CONF="ACME (ACME_USB: $ACME_USB @ ACME_IP: $ACME_IP, ACME_CHANNELS: $ACME_CHANNELS)"
	;;
'MONSOON')
	EMETER_CONF="MONSOON (all defaults)"
	;;
*)
	c_error "Energy meter [EMETER=$EMETER] not supported"
	exit $EINVAL
	;;
esac

# Report current setup
box_out \
	"Mandatory conf" \
	"   PLATFORM      : $PLATFORM" \
	"   KERNEL_SRC    : $KERNEL_SRC" \
	"   SERIES        : $SERIES" \
	"   WA_AGENDA     : $WA_AGENDA" \
	"   RESULTS       : $TEST_CMD_RESULTS" \
	"" \
	"Tools" \
	"   ADB           : $ADB" \
	"   FASTBOOT      : $FASTBOOT" \
	"" \
	"Energy meter" \
	"   EMETER        : $EMETER_CONF" \
	"   DEVICE        : $DEVICE" \
	"" \
	"Internals" \
	"   Scripts dir   : $BASE_DIR" \
	"   FORCE         : $FORCE" \
	"   DRYRUN        : $DRYRUN"

################################################################################
# Device access via USB connection management
################################################################################
usb_disconnect() {
	c_info "Disconnecting USB..."
	if [ $DRYRUN ]; then return; fi
	case $EMETER in
	'ACME')
		sh root@$ACME_IP \
			"echo 0 > /sys/bus/iio/devices/iio:$ACME_USB/in_active"
		;;
	'MONSOON')
		# not supported for now
		c_warn "Energy meter $EMETER does not support usb_disconnect"
		;;
	*)
		c_error "Energy meter $EMETER not supported"
		exit $EINVAL
		;;
	esac
}

usb_connect() {
	c_info "Connecting USB..."
	if [ $DRYRUN ]; then return; fi
	case $EMETER in
	'ACME')
		ssh root@$ACME_IP \
			"echo 1 > /sys/bus/iio/devices/iio:$ACME_USB/in_active"
		;;
	'MONSOON')
		# not supported for now
		c_warn "Energy meter $EMETER does not support usb_connect"
		;;
	*)
		c_error "Energy meter $EMETER not supported"
		exit $EINVAL
		;;
	esac
	sleep 5
}

################################################################################
# FASTBOOT mode checking
################################################################################
device_in_fastboot() {
	[[ $(fastboot devices | grep -e "$DEVICE.*fastboot" | wc -l) -gt 0 ]] || return $ENODEV
	return $OK
}
device_not_in_fastboot() {
	device_in_fastboot || return $OK
	return $EAGAIN
}

################################################################################
# ADB mode checking
################################################################################
device_in_adb() {
	[[ $(adb devices | grep -e "$DEVICE.*device" | wc -l) -gt 0 ]] || return $ENODEV
	return $OK
}
device_not_in_adb() {
	device_in_adb || return $OK
	return $EAGAIN
}

################################################################################
# Utility Android commands
################################################################################
device_wake() {
	device_in_adb || return $EAGAIN
	$ADB shell input keyevent KEYCODE_MENU
	sleep 3
	$ADB shell input keyevent KEYCODE_MENU
	return $OK
}
device_not_wake() {
	device_wake || return $OK
	return $EAGAIN
}

################################################################################
# DEVICE connection checks
################################################################################
device_connected() {
	seconds=${1:-5}

	[ $DRYRUN -eq 1 ] || \
	while [[ true ]]; do
		device_not_in_fastboot || return $OK
		device_not_in_adb || return $OK

		echo
		c_warning "Device not in FASTBOOT nor in ADB mode"
		let seconds--
		if [[ $seconds -eq 0 ]]; then
			c_error "device not connected"
			return $ENODEV
		fi
		usb_disconnect
		c_warning "Check again in 1s..."
		sleep 1
		usb_connect
	done
	return $OK
}
device_not_connected() {
	device_connected || return $OK
	return $EAGAIN
}

device_status() {
	_CNT='NO'; device_connected || _CNT='NO'
	_FBT='NO'; device_in_fastboot || _FBT='NO'
	_ADB='NO'; device_in_adb || _ADB='NO'
	c_info "Current device Status"
	c_info "Reachable : $_CNT"
	c_info "Fastboot  : $_FBT"
	c_info "ADB Mode  : $_ADB"
}

################################################################################
# DEVICE boot checks
################################################################################
reboot_timedout() {
	[ $ELAPSED -lt $REBOOT_TIMEOUT ] || return $OK
	return $EAGAIN
}
reboot_not_timedout() {
	reboot_timedout || return $OK
	return $EAGAIN
}

boot_completed() {
	COMPLETED=$($ADB shell getprop sys.boot_completed)
	[[ "x$COMPLETED" = x1* ]] || return $EAGAIN
	return $OK
}
boot_not_completed() {
	boot_completed || return $OK
	return $EAGAIN
}


################################################################################
# Reboot into different modes
################################################################################
enter_fastboot() {
	seconds=$1

	# Check device is connected
	if device_not_connected; then
		c_error "device not connected"
		return $ENODEV
	fi

	# Already in fastboot mode: nothing to do
	if device_in_fastboot; then
		c_info "Device already in fastboot mode, continuing..."
		return $OK
	fi

	c_info "Device in ADB mode"
	c_info "Rebooting into bootloader..."
	[ $DRYRUN -eq 1 ] || $ADB reboot bootloader

	echo
	c_info "Waiting for bootloader up to $REBOOT_TIMEOUT[s]..."
	ELAPSED=0
	sleep 5

	# Wait for device to leave ADB mode
	[ $DRYRUN -eq 1 ] || \
	until device_not_in_adb || reboot_timedout; do
		sleep 3; let ELAPSED+=3
	done
	echo
	if reboot_timedout; then
		c_error "device not leaving ADB mode"
		d_notify "Bootloader enter TIMEOUT!" face-embarrassed
		exit $EIO
	fi

	# Wait for device to enter FASTBOOT mode
	[ $DRYRUN -eq 1 ] || \
	while device_not_in_fastboot && reboot_not_timedout; do
		usb_disconnect &>/dev/null
		sleep 3; let ELAPSED+=3
		usb_connect &>/dev/null
	done
	echo
	if reboot_timedout; then
		c_error "device not entering in FASTBOOT mode"
		d_notify "Bootloader enter TIMEOUT!" face-embarrassed
		exit $EIO
	fi

	# Ensure we are in FASTBOOT mode, otheriwse we have to try again...
	[ $DRYRUN -eq 0 ] || return $OK
	device_in_fastboot || return $EAGAIN

	return $OK
}

reboot_fastboot() {
	echo
	c_info "Rebooting device into FASTBOOT..."
	attempts=3
	enter_fastboot; RESULT=$?
	while [[ $RESULT -ne OK ]]; do
		let attempts--
		if [[ $attempts -eq 0 ]]; then
			c_error "device not entering FASTBOOT mode"
			exit $EIO
		fi
		c_warning "Failed entering FASTBOOT mode, $attempts remaining attempts..."
		enter_fastboot; RESULT=$?
	done
}

################################################################################
# ADB mode
################################################################################
enter_adb() {

	[ $DRYRUN -eq 0 ] || return $OK

	# Check device is connected
	if device_not_connected; then
		c_error "device not connected"
		return $ENODEV
	fi

	# Already in adb mode: nothing to do
	if device_in_adb; then
		c_info "Device already in adb mode, continuing..."
		return $OK
	fi

	echo
	c_info "Device in FASTBOOT mode"
	c_info "Booting device..."
	[ $DRYRUN -eq 1 ] || $FASTBOOT reboot

	c_info "Waiting up to $REBOOT_TIMEOUT[s] for boot to complete..."
	ELAPSED=0

	#### Wait for device to reboot
	[ $DRYRUN -eq 1 ] || \
	until device_in_adb || reboot_timedout; do
		usb_disconnect &>/dev/null
		sleep 3; let ELAPSED+=3
		usb_connect &>/dev/null
	done
	echo
	if reboot_timedout; then
		c_error "device not entering ADB mode"
		d_notify "Device reboot TIMEOUT!" face-embarrassed
		exit $EIO
	fi
	c_info "Device in ADB mode"

	### Wait for boot to complete
	[ $DRYRUN -eq 1 ] || \
	until boot_completed || reboot_timedout; do
		sleep 3; let ELAPSED+=3
	done
	echo
	if reboot_timedout; then
		c_error "device still booting?!?"
		d_notify "Device boot completion TIMEOUT!" face-embarrassed
		exit $EIO
	fi

	# Ensure we are in ADB mode, otheriwse we have to try again...
	[ $DRYRUN -eq 0 ] || return $OK
	device_in_adb || return $EAGAIN

	return $OK
}

reboot_adb() {
	echo
	c_info "Rebooting device into ADB..."
	attempts=3
	enter_adb; RESULT=$?
	while [[ $RESULT -ne $OK ]]; do
		let attempts--
		if [[ $attempts -eq 0 ]]; then
			c_error "device not entering ADB mode"
			exit $EIO
		fi
		c_warning "Failed entering ADB mode, $attempts remaining attempts..."
		enter_adb; RESULT=$?
	done
}

################################################################################
# Build and test a specified SHA1 checkout
################################################################################

name_sha1() {
	COMMIT_SHA1=${1%% *}
	MINLEN=12345

	# In case the specified SHA1 has not a name, let's use the SHA1
	COMMIT_NAME=$COMMIT_SHA1

	# Find a name for each possible REF
	mkfifo tmp_pipe &>/dev/null
	git -C $KERNEL_SRC for-each-ref \
			--sort=-committerdate \
			--format='%(objectname:short) %(refname:short)' \
			refs/heads/ refs/remotes/ refs/tags |
	grep $COMMIT_SHA1 | awk '{print $2}' > tmp_pipe &
	while IFS= read -r NAME; do
		# Return the fist name starting by "test_"
		if [[ $NAME = test_* ]]; then
			COMMIT_NAME=${NAME//\//:}
			break
		fi
		# Or the shorted name for a given SHA1
		if [ ${#NAME} -lt $MINLEN ]; then
			MINLEN=${#NAME}
			COMMIT_NAME=${NAME//\//:}
		fi
	done < tmp_pipe
	rm tmp_pipe
}

match_sha1() {
	COMMIT_SHA1=$1

	c_info "Current kernel: "
	c_info "   $($ADB shell 'uname -a')"

	CURRENT=$($ADB shell 'uname -r' | awk -F "-g" '{print $NF}')
	[[ $COMMIT_SHA1 =~ $CURRENT* ]] && return $OK

	# It may happen that a tag pointing to a given commit has
	# a different SHA1 (signed tag), so check if this this is
	# the case.
	TAG_NAME=$(git -C $KERNEL_SRC describe --exact-match $COMMIT_SHA1 2>/dev/null) || return $EAGAIN
	TAG_SHA1=$(git -C $KERNEL_SRC show-ref --hash $TAG_NAME)
	c_info "   CommitID of local repo corresponds to tag: $TAG_NAME"
	[[ $TAG_SHA1 =~ $CURRENT* ]] && return $OK

	return $EAGAIN
}

build_sha1() {
	COMMIT_SHA1=$1
	COMMIT_DESC=$2

	### Prepare KERNEL_SRC for build
	pushd $KERNEL_SRC &>/dev/null
	echo
	c_info "Checkout kernel: $KERNEL_SRC @ $COMMIT_SHA1..."
	git checkout $COMMIT_SHA1; ERROR=$?
	if [ $ERROR -ne 0 ]; then
		c_error "Failed to checkout [$COMMIT_SHA1]"
		popd &>/dev/null
		return $ERROR
	fi
	popd &>/dev/null

	### Build all IMAGES
	pushd $BASE_DIR &>/dev/null
	$PLATFORM_PATH/build_images
	RESULT=$?
	popd &>/dev/null
	if [ $RESULT -ne $OK ]; then
		exit $ENOENT
	fi
	[ $RESULT -eq $OK ] || return $RESULT
}

flash_sha1() {
	COMMIT_SHA1=$1
	COMMIT_DESC=$2

	build_sha1 "$COMMIT_SHA1" "$COMMIT_DESC"; RESULT=$?
	[ $RESULT -eq $OK ] || return $RESULT

	### Flash generated IMAGES
	[ $DRYRUN -eq 0 ] || return $OK
	pushd $PLATFORM_PATH/artifacts &>/dev/null

	# Before: flash images in ADB (e.g. push new modules)
	c_info "Flash images from ADB mode..."
	reboot_adb
	[ $DRYRUN -eq 1 ] || \
		$PLATFORM_PATH/flash_images ADB; RESULT=$?
	[ $RESULT -eq $OK ] || return $RESULT

	# Then: flash images in FASTBOOT mode (e.g. kernel and dtbo images)
	c_info "Flash images from FASTBOOT mode..."
	reboot_fastboot
	[ $DRYRUN -eq 1 ] || \
		$PLATFORM_PATH/flash_images FASTBOOT; RESULT=$?
	[ $RESULT -eq $OK ] || return $RESULT

	# Flashing completed, check for success...
	popd &>/dev/null
	reboot_adb

	c_info "Boot completed, wait 10[s] more..."
	sleep 10 # Add an additional safe margin

	### Check that we are running the expected kernel
	match_sha1 $COMMIT_SHA1; ERROR=$?
	[ $ERROR -eq 0 ] || c_error "Failed to flash kernel [$COMMIT_DESC]!"
	return $?
}

test_sha1() {
	COMMIT_SHA1=$1
	COMMIT_ID=$2
	COMMITS_COUNT=$3
	COMMIT_DESC="$(grep $COMMIT_SHA1 $SERIES)"

	# Get a name (if any) for the specified SHA1
	name_sha1 $COMMIT_SHA1
	c_info "Testing kernel:"
	c_info "   SeriesID   : $COMMIT_DESC"
	c_info "   CommitID   : $COMMIT_SHA1 $COMMIT_NAME"

	echo
	c_info "Check current kernel..."
	if device_in_adb; then
		DEVICE_OS_VERSION=$($ADB shell getprop ro.build.version.release)
		DEVICE_OS_PATCH_LEVEL=$($ADB shell getprop ro.build.version.security_patch)

		export ANDROID_OS_VERSION=${ANDROID_OS_VERSION:-$DEVICE_OS_VERSION}
		export ANDROID_OS_PATCH_LEVEL=${ANDROID_OS_PATCH_LEVEL:-$DEVICE_OS_PATCH_LEVEL}

		echo
		c_info "Android version      : $ANDROID_OS_VERSION"
		c_info "Security patch level : $ANDROID_OS_PATCH_LEVEL"

		match_sha1 $COMMIT_SHA1
		if [ $? -ne $OK ]; then
			c_info "Kernel update required!"
			flash_sha1 $COMMIT_SHA1 "$COMMIT_DESC"; RESULT=$?
			[[ $RESULT -ne $EIO ]] || exit $EIO
			if [[ $RESULT -ne 0 ]]; then
				c_warning "Skipping kernel [$COMMIT_DESC]"
				return
			fi
		fi
	else
		c_warning "Device not connected via ADB, cannot check current kernel"
		c_warning "Forcing: build, flashing and reboot selected kernel"
		flash_sha1 $COMMIT_SHA1 "$COMMIT_DESC"; RESULT=$?
		[[ $RESULT -ne $EIO ]] || exit $EIO
		if [[ $RESULT -ne 0 ]]; then
			c_warning "Skipping kernel [$COMMIT_DESC]"
			d_notify "Skipping kernel [$COMMIT_DESC]" face-sick
			return
		fi
	fi

	echo

	c_info "Wakeup the device"
	if device_not_wake; then
		c_warning "Device not awake, cannot test current kernel"
		c_warning "Skipping kernel [$COMMIT_DESC]"
		d_notify "Skipping kernel [$COMMIT_DESC]" face-sick
		return
	fi

	c_info "Running tests for [$COMMIT_SHA1: $COMMIT_NAME]..."
	d_notify "Testing kernel $COMMIT_ID/$COMMITS_COUNT:\n$COMMIT_SHA1: $COMMIT_NAME..." face-tired
	[ $DRYRUN -eq 1 ] || (set -x; eval $TEST_CMD; set +x)
}

report() {

if [[ $TEST_CMD = *"wa run"* ]]; then
	# Check for ERRORs reported in WorkloadAutomation log files
	c_info "Looking for WA errors..."
	ERRORS=$(find $RESULTS -name run.log \
		 -exec grep "WARNING    executor: Please see" \{\} \;)
	if [ -z "$ERRORS" ]; then
		c_info "No Errors reported in WA logfiles"
	else
		c_warning "WA reported these errors:"
		echo $ERRORS | while read ERR; do
			c_warning "   $(echo $ERR | awk '{print $7}')";
		done
	fi
fi

}

# Prepare list of commits to test
SELECTED_LIST="$(realpath $SERIES).selected"
FMT=$(grep -v "^#" $SERIES | grep -v "00: " | head -n1 | awk '{print $1}')
if [[ $FMT = *: ]]; then
	# Filter out disabled commits and sort based on progressive ID:
	grep -E -v "^$|^#|00: " $SERIES | sort \
		| awk '{$1=""; print $0}' > $SELECTED_LIST
else
	grep -E -v "^$|^#" $SERIES \
		| awk '{print $0}' > $SELECTED_LIST
fi

# Report commits to be tested
COMMIT_ID=0
echo
c_info "Commits selected for testing:"
cat $SELECTED_LIST | \
while read COMMIT; do
	let COMMIT_ID++
	STR=$(printf "  %3s %s\n" $COMMIT_ID "$COMMIT")
	c_info "$STR"
done

# Extract total number of commits
COMMITS_COUNT=$(wc -l $SELECTED_LIST)
COMMITS_COUNT=${COMMITS_COUNT%% *}

# Ensure USB is on at tests start
usb_connect 1>/dev/null
printf "\n%80s\n\n" | tr " " "="

# If the target isn't connected at the start, bail out
device_connected || exit 1

# Test each commit
COMMIT_ID=1
# Here we read from an arbitrary file descriptor 10 to avoid overlaps with
# stdin generated by the adb commands in the loop body
while read -u10 COMMITS; do
	# Extract commit identifier from commit description
	COMMIT=${COMMITS%% *}

	# Translate possible branch name to SHA1
	COMMITS=$(git -C $KERNEL_SRC show-ref -s $COMMIT)
	if [ $? -ne 0 ]; then
		COMMIT_SHA1=$COMMIT
	elif [ $(echo $COMMITS | wc -w) -eq 1 ]; then
		COMMIT_SHA1=$COMMITS
	else
		c_error "The branch name must be univocal, \"$COMMIT\" may refer to:"
		for b in $(git -C $KERNEL_SRC show-ref $COMMIT | cut -f 2 -d " "); do
			c_error "    $b"
		done
		exit $EINVAL
	fi

	box_out "PROGRESS : $COMMIT_ID/$COMMITS_COUNT" \
		"COMMIT   : $COMMITS"
	echo
	device_status

	echo
	test_sha1 $COMMIT_SHA1 $COMMIT_ID $COMMITS_COUNT

	let COMMIT_ID++
	printf "\n%80s\n\n" | tr " " "="

done 10<$SELECTED_LIST

# Generate reports
report

d_notify "Tests completed!" face-cool
