#
# LISA documentation build configuration file, created by
# sphinx-quickstart on Tue Dec 13 14:20:00 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import logging
import os
import re
import subprocess
import sys
import unittest
import textwrap
import json
import functools
import inspect
import importlib
import types
import contextlib
from pathlib import Path
import importlib
from operator import attrgetter
import pickle
import shutil

from sphinx.domains.python import PythonDomain


# Signal to lisa.utils.is_running_sphinx() that we are indeed running under
# sphinx before we import anything
os.environ['_LISA_DOC_SPHINX_RUNNING'] = '1'

# This shouldn't be needed, as using a virtualenv + setup.py should set up the
# sys.path correctly. However that seems to be half broken on ReadTheDocs, so
# manually set it here
sys.path.insert(0, os.path.abspath('../'))

# Import our packages after modifying sys.path
import lisa
from lisa.utils import sphinx_nitpick_ignore, setup_logging, get_obj_name, DirCache
from lisa._doc.helpers import (
    autodoc_process_test_method, autodoc_process_analysis_events,
    autodoc_process_analysis_plots, autodoc_process_analysis_methods,
    autodoc_skip_member_handler, autodoc_process_inherited_members,
    autodoc_process_inherited_signature, autodoc_process_bases_handler,
    DocPlotConf, autodoc_pre_make_plots,
    intersphinx_warn_missing_reference_handler,
)

import devlib

def prepare(home, enable_plots):
    # This ugly hack is required because by default TestCase.__module__ is
    # equal to 'case', so sphinx replaces all of our TestCase uses to
    # unittest.case.TestCase, which doesn't exist in the doc.
    for name, obj in vars(unittest).items():
        try:
            m = obj.__module__
            obj.__module__ = 'unittest' if m == 'unittest.case' else m
        except Exception:
            pass



    def run(cmd, **kwargs):
        return subprocess.run(
            cmd,
            cwd=home,
            **kwargs,
        )

    # In case we have a shallow clone, make sure to have the whole
    # history to be able to generate breaking change list and any other
    # git-based documentation
    run(['git', 'fetch', '--unshallow'], check=False)
    run(['git', 'fetch', '--tags'], check=False)

    # Ensure we have the changelog notes that supplement commit messages, as
    # sometimes the markers such as FEATURE were forgotten and later added
    # using git notes.
    run(['git', 'fetch', 'origin', 'refs/notes/changelog'])

    source_env = {
        **os.environ,
        # LISA_USE_VENV=0 will avoid re-installing LISA automatically,
        # which would be useless.
        'LISA_USE_VENV': '0',
    }
    # If LISA_HOME is set, sourcing the script won't work
    source_env.pop('LISA_HOME', None)

    init_env = home / 'init_env'
    script = textwrap.dedent(
        f"""
        source {init_env} >&2 &&
        python -c 'import os, json; print(json.dumps(dict(os.environ)))'
        """
    )
    out = subprocess.check_output(
        ['bash', '-c', script],
        cwd=home,
        # Reset the environment, including LISA_HOME to allow sourcing without
        # any issue
        env=source_env,
    )
    os.environ.update(json.loads(out))

    # Re-run the notebook to ensure the version of bokeh used is the same as
    # the one that will be added via html_js_files. Otherwise, the plot display
    # will be broken.
    notebooks_in_base = Path(home, 'ipynb')
    notebooks = [
        'examples/analysis_plots.ipynb',
    ]
    if enable_plots:
        def populate(key, temp_path):
            # We pre-generate all the plots, otherwise we would end up running
            # polars code in a multiprocessing subprocess created by forking
            # CPython, leading to deadlocks:
            # https://github.com/sphinx-doc/sphinx/issues/12201
            hv.extension('bokeh')

            plot_conf_path = Path(home, 'doc', 'plot_conf.yml')
            plot_conf = DocPlotConf.from_yaml_map(plot_conf_path)
            plots = autodoc_pre_make_plots(plot_conf)
            with open(temp_path / 'plots.pickle', 'wb') as f:
                pickle.dump(plots, f)

            for _path in notebooks:
                in_path = notebooks_in_base / _path
                out_path = temp_path / 'ipynb' / _path
                out_path.parent.mkdir(parents=True, exist_ok=True)
                try:
                    out_path.unlink()
                except FileNotFoundError:
                    pass
                logging.info(f'Refreshing notebook: {in_path}')
                subprocess.check_call([
                    'jupyter',
                    'nbconvert',
                    in_path,
                    '--execute',
                    '--to=notebook',
                    f'--output={out_path}'
                ])

        import holoviews as hv
        import bokeh
        import panel as pn
        import jupyterlab

        dir_cache = DirCache('doc_plots', populate=populate)
        key = (
            hv.__version__,
            bokeh.__version__,
            pn.__version__,
            jupyterlab.__version__,
        )
        cache_path = dir_cache.get_entry(key)
        with open(cache_path / 'plots.pickle', 'rb') as f:
            plots = pickle.load(f)

        for _path in notebooks:
            shutil.copy2(
                cache_path / 'ipynb' / _path,
                Path(home, 'doc', 'workflows', 'ipynb') / _path,
            )

    else:
        plots = {}
        for _path in notebooks:
            shutil.copy2(
                notebooks_in_base / _path,
                Path(home, 'doc', 'workflows', 'ipynb') / _path,
            )

    return plots



# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'lisa._doc.helpers',
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.inheritance_diagram',
    'sphinxcontrib.plantuml',
    'nbsphinx',
]

RTD = (os.getenv('READTHEDOCS') == 'True')
if RTD:
    pass

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
}

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'LISA'
copyright = '2024, ARM-Software'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
version = str(lisa.__version__)
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'pydata_sphinx_theme'


# Allow interactive bokeh plots in the documentation
try:
    import bokeh.resources
except ImportError:
    pass
else:
    html_js_files = bokeh.resources.CDN.js_files
    html_css_files = bokeh.resources.CDN.css_files

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

# For pydata theme
html_theme_options = {
    # Increase show_toc_level value to get API listings in sidebar
    "show_toc_level": 2,
}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'LISAdoc'

html_theme_options['announcement'] = f'''
<p>
<span class="versionmodified deprecated">
    This documentation was obtained by building the "master" git branch. LISA
    project has moved to the "main" branch.  The "master" branch is now a
    mirror of "main" but will eventually be abandonned, please see the
    <a href="https://tooling.sites.arm.com/lisa/latest">latest
    documentation</a>.
</span>
</p>

{html_theme_options.get('announcement', '')}
'''

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    ('index', 'LISA.tex', 'LISA Documentation',
   'ARM-Software', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'lisa', 'LISA Documentation',
     ['ARM-Software'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'LISA', 'LISA Documentation',
   'ARM-Software', 'LISA', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'holoviews': ('https://holoviews.org/', None),
    'polars': ('https://docs.pola.rs/py-polars/html/', None),
    # XXX: Doesn't seem to work, might be due to how devlib doc is generated
    'devlib': ('https://devlib.readthedocs.io/en/latest/', None),
    'wa': ('https://workload-automation.readthedocs.io/en/latest/', None),
    'ipywidgets': ('https://ipywidgets.readthedocs.io/en/latest/', None),
    'IPython': ('https://ipython.readthedocs.io/en/stable/', None),
    'typeguard': ('https://typeguard.readthedocs.io/en/stable/', None),
}

manpages_url = "https://manpages.debian.org/{path}"

#
# Fix autodoc
#

# Include __init__ docstrings (obviously)
autoclass_content = 'both'

autodoc_member_order = 'bysource'

autodoc_default_options = {
    # Show the members of the documented entity (e.g. class or module)
    'members': None,
    # autodoc_process_inherited_members() will replace docstrings for each
    # inherited member instance with a stub that links to the definition in the
    # base class. That sidesteps the issue of the docstring of the inherited
    # member not being valid reST.
    'inherited-members': None,
    # Show parent class
    'show-inheritance': None,
    # Show members even if they don't have docstrings
    'undoc-members': None,
    # Show special methods such as __and__
    'special-members': None,
    # Note: we make use of it in our custom autodoc-skip-member hook to ensure
    # it is always honored, even when some members are explicitly excluded.
    # On top of that, some functions are always excluded (see the hook
    # implementation for the details).
    'exclude-members': ','.join([
        # All the classes in lisa have their __init__ signature documented in
        # the class docstring
        '__init__',

        # Uninteresting
        '__doc__',
        '__weakref__',
        '__module__',
        '__abstractmethods__',
        '__slotnames__',
        '__eq__',
        '__str__',
        '__repr__',
        '__dict__',
        '__annotations__',
        '__instance_dir__',
    ])
}
autodoc_inherit_docstrings = True

non_ignored_refs = {
    r'lisa\..*',
}
non_ignored_refs = set(map(re.compile, non_ignored_refs))


# Workaround for: https://github.com/jupyter-widgets/ipywidgets/issues/3930
# Suggested: https://github.com/sphinx-doc/sphinx/issues/12585#issuecomment-2228420035
suppress_warnings = [
    'intersphinx.external',
]


# Workaround for: https://github.com/sphinx-doc/sphinx/issues/11279
viewcode_follow_imported_members = False


def setup(app):
    setup_logging(level=logging.INFO)

    # Do not rely on LISA_HOME as it may not be set and will default to current
    # folder, which is not what we want here.
    home = Path(__file__).parent.parent.resolve()

    enable_plots = bool(int(os.environ.get('LISA_DOC_BUILD_PLOT', '1')))

    plots = prepare(
        home=home,
        enable_plots=enable_plots,
    )

    _autodoc_process_analysis_plots_handler = functools.partial(
        autodoc_process_analysis_plots,
        plots={
            get_obj_name(x): fig
            for x, fig in plots.items()
        }
    )
    _autodoc_skip_member_handler = functools.partial(
        autodoc_skip_member_handler,
        default_exclude_members=autodoc_default_options.get('exclude-members')
    )
    _intersphinx_warn_missing_reference_handler = functools.partial(
        intersphinx_warn_missing_reference_handler,
        non_ignored_refs=non_ignored_refs,
    )

    # Use a custom class so that a confused user could easily find it back in
    # the sources.
    class ExecState:
        def __init__(self, plots):
            self.plots = plots

    app.connect('warn-missing-reference', _intersphinx_warn_missing_reference_handler, priority=0)
    app.connect('autodoc-process-docstring', autodoc_process_test_method)
    app.connect('autodoc-process-docstring', autodoc_process_analysis_methods)
    app.connect('autodoc-process-docstring', autodoc_process_analysis_events)
    app.connect('autodoc-process-docstring', _autodoc_process_analysis_plots_handler)

    # Applied at the end to ensure we can just fully replace the docstring content whole
    app.connect('autodoc-process-docstring', autodoc_process_inherited_members)
    app.connect('autodoc-process-signature', autodoc_process_inherited_signature)
    app.connect('autodoc-process-bases', autodoc_process_bases_handler)

    app.connect('autodoc-skip-member', _autodoc_skip_member_handler)
    app.connect('lisa-exec-state', lambda app: ExecState(plots=plots))

# vim :set tabstop=4 shiftwidth=4 textwidth=80 expandtab:
