#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2018, Arm Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ret=0

cd "$LISA_HOME/doc" || exit 1

##############################
# Build the main documentation
##############################

make SPHINXOPTS='-n --no-color -W --keep-going -T -j auto' html || ret=1

echo
echo "Building man pages"
echo

#################
# Build man pages
#################

docs=(
    "tools/bisector/doc/man/"
    "tools/exekall/doc/man/"
    "doc/lisa_shell/man"
)

for doc in "${docs[@]}"; do
    sphinx-build "$LISA_HOME/$doc" "$LISA_HOME/doc/man1" -Enab man || ret=2
done

echo "Man pages have been updated and the main documentation can be found under: $LISA_HOME/doc/_build/html/index.html"

[[ $ret = 0 ]] || echo "ERROR: some non-ignore warnings appeared during the build"
exit $ret
