#! /usr/bin/env python3
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2018, Arm Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

import argparse
import sys

def main():
    try:
        from lisa.utils import LISA_HOME
        import lisa._git as git
        from lisa._doc.helpers import make_changelog
    except ImportError:
        print("Cannot import lisa, LISA news skipped")
        return 0
    else:
        parser = argparse.ArgumentParser(description='''
            Show noteworthy news since last git pull
            '''
        )

        parser.add_argument('--since',
            required=True,
            help='Show what is new since the given git ref',
        )

        parser.add_argument('--repo',
            default=LISA_HOME,
            help='Path to LISA git repo',
        )

        args = parser.parse_args()
        repo = args.repo
        since = args.since

        since_date = git.git(repo, 'show', '-s', '--format=%ci', since).strip()
        since_date_rel = git.git(repo, 'show', '-s', '--format=%cr', since).strip()

        changelog = make_changelog(
            repo,
            since=since,
            head_release_name=f'Changes since {since_date_rel} ({since_date})',
            fmt='txt',
        )
        print(changelog)
        return 0

if __name__ == '__main__':
    sys.exit(main())

# vim :set tabstop=4 shiftwidth=4 textwidth=80 expandtab
