#! /bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2021, ARM Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cat <<EOF
LISA version $(python -c 'import lisa; print(lisa.__version__)'):
    $LISA_HOME
    version token: $(python -c 'import lisa.version as v; print(v.VERSION_TOKEN)')
    branch: $(git -C "$LISA_HOME" describe --all)
    commit: $(git -C "$LISA_HOME" rev-parse --short=11 HEAD)


Python version: $PYTHON_VERSION

EOF

if which jupyter >/dev/null; then
    jupyter labextension list 2>&1
fi
