#! /bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2019, ARM Limited and contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

if [[ -e "$LISA_CONF" ]]; then
	conf_opt=('--conf' "$LISA_CONF")
else
	conf_opt=()
fi

latest_link="$LISA_HOME/$("$LISA_PYTHON" -c 'from lisa.utils import LATEST_LINK; print(LATEST_LINK)')"

cmd=(
  exekall run lisa lisa_tests				\
	"${conf_opt[@]}"									\
	--symlink-artifact-dir-to "$latest_link"			\
	--share '*.Target'									\
	--select-multiple									\
	"$@"
)

# Show the command before running, so --help makes more sense
printf '%q ' "${cmd[@]}"
echo

exec "${cmd[@]}"
