#! /usr/bin/env bash

# ENSURE THE GIT TREE DOES NOT CONTAIN ANY EXTRA FILE, AS THEY MIGHT BE
# INCLUDED IN THE WHEEL (especially in lisa/_assets/)

# Inspired by: https://packaging.python.org/tutorials/packaging-projects/
set -e
cd "$LISA_HOME" || (echo "Could not cd to $LISA_HOME"; exit 1)

version=$($LISA_PYTHON -c 'import lisa; print(lisa.__version__)')

git tag -f "v$version"

rm -r dist/ || true
$LISA_PYTHON -m build
#$LISA_PYTHON -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*
