[devlib]
path = external/devlib
url = https://gitlab.arm.com/tooling/workload-automation/devlib.git
ref = main

# See external/devlib.manifest.yaml for instructions on how to build this
# branch:
# url = https://github.com/douglas-raillard-arm/devlib.git
# ref = lisa

[workload-automation]
path = external/workload-automation
url = https://gitlab.arm.com/tooling/workload-automation/workload-automation.git
ref = main

# See external/workload-automation.manifest.yaml for instructions on how to
# build this branch:
# url = https://github.com/douglas-raillard-arm/workload-automation.git
# ref = lisa
