/* SPDX-License-Identifier: GPL-2.0 */

/* Generated with cbindgen:0.27.0 */

/* Warning, this file is autogenerated by Rust cbindgen. Don't modify this manually. */



extern uint8_t *__lisa_rust_alloc(size_t size);

extern uint8_t *__lisa_rust_alloc_zeroed(size_t size);

extern void __lisa_rust_dealloc(uint8_t *ptr);

extern void __lisa_rust_panic(const uint8_t *msg, size_t len);

extern void __lisa_rust_pr_info(const uint8_t *msg, size_t len);

extern uint8_t *__lisa_rust_realloc(uint8_t *ptr, size_t size);

extern uint64_t myc_callback(uint64_t x);

 uint64_t test_1(uint64_t left, uint64_t right) ;

 uint64_t test_2(uint64_t left, uint64_t right) ;

 uint64_t test_3(uint64_t left, uint64_t right) ;


