name: mirror

on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  mirror:
    name: mirror
    # Set the type of machine to run on
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    steps:

      # Checks out a copy of your repository on the virtual machine
      - uses: actions/checkout@v2
        with:
          # Avoid a shallow clone
          fetch-depth: "0"
          ref: ${{ github.sha }}

      - name: Setup git
        run: |
          git config --global user.name 'GitHub action'
          git config --global user.email 'douglas-raillard-arm@users.noreply.github.com'

          git remote -v
          git branch --list --remotes

      - name: Mirror branches
        run: git push origin origin/master:main
