name: mirror

on:
  # Run the workflow when any branch is pushed
  push: null

permissions:
  # Necessary to be able to push to the repo
  contents: write

jobs:
  mirror:
    name: mirror

    # Ensure jobs queue in order, so that we don't get race conditions while
    # pushing the branch
    concurrency: mirror

    # Set the type of machine to run on
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    steps:

      # Checks out a copy of your repository on the virtual machine
      - uses: actions/checkout@v3
        with:
          # Avoid a shallow clone
          fetch-depth: "0"
          ref: ${{ github.sha }}

      - name: Setup git
        run: |
          git config --global user.name 'GitHub Action'

          git remote -v
          git branch --list --remotes

      - name: Mirror main
        run: git push origin origin/master:main
