name: preview

on:
  # Whenever a pull request is labeled or unlabeled.
  pull_request_target:
    types: [labeled, unlabeled, synchronize]

  # To be able to manually trigger the job from GitHub UI
  workflow_dispatch:

  # Run the workflow when the base branch is updated.
  push:
    branches:
      - 'main'

permissions:
  # Necessary to be able to push to the repo
  contents: write

jobs:
  preview:
    name: preview
    # Set the type of machine to run on
    # https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    if: |
      ${{
          (
              github.event_name == 'pull_request_target' &&
              (
                  (
                      github.event.action == 'synchronize' &&
                      contains(github.event.pull_request.labels.*.name, 'preview')
                  ) ||
                  (
                      (
                          github.event.action == 'labeled' ||
                          github.event.action == 'unlabeled'
                      ) &&
                      github.event.label.name == 'preview'
                  )
              )
          ) ||
          github.event_name != 'pull_request_target'
      }}

    steps:

      # Checks out a copy of your repository on the virtual machine
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Setup git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'GitHub Action'

          git remote -v
          git branch --list --remotes

      - name: Create preview branch
        run: |
          set -e
          source init_env
          lisa-make-preview
          git push origin preview --force
